INSERT INTO `kupac` (`kupac_id`, `ime`, `prezime`, `grad`, `adresa`, `telefon`, `user`, `pass`) VALUES (1, 'Azra', 'Pamuk', 'Sarajevo', 'Bunica 41', '062614454', 'azra.pamuk', 'admin');
INSERT INTO `kupac` (`kupac_id`, `ime`, `prezime`, `grad`, `adresa`, `telefon`, `user`, `pass`) VALUES (2, 'Envera', 'Mulahasanović', 'Sarajevo ', 'Harisa Kapetanovića 25', '062588987', 'envera.mulahasanovic', '2envera');
INSERT INTO `kupac` (`kupac_id`, `ime`, `prezime`, `grad`, `adresa`, `telefon`, `user`, `pass`) VALUES (3, 'Mina', 'Trgo', 'Sarajevo', 'Plavi put 5', '061589745', 'mina.trgo', '3mina');
INSERT INTO `kupac` (`kupac_id`, `ime`, `prezime`, `grad`, `adresa`, `telefon`, `user`, `pass`) VALUES (4, 'Erduana', 'Bećar', 'Sarajevo', 'Safeta Zajke 58', '063589745', 'erduana.becar', '4erduana');
INSERT INTO `kupac` (`kupac_id`, `ime`, `prezime`, `grad`, `adresa`, `telefon`, `user`, `pass`) VALUES (5, 'Amina', 'Bicić', 'Tuzla', 'Petra Kočića 6', '062365478', 'amina.bicic', '5amina');
INSERT INTO `kupac` (`kupac_id`, `ime`, `prezime`, `grad`, `adresa`, `telefon`, `user`, `pass`) VALUES (6, 'Faruk', 'Hodžić', 'Zenica', 'Krivače 30', '061265555', 'faruk.hodzic', '6faruk');
INSERT INTO `kupac` (`kupac_id`, `ime`, `prezime`, `grad`, `adresa`, `telefon`, `user`, `pass`) VALUES (7, 'Lejla', 'Majić', 'Bihać', 'Muhsina Rizvića 5', '0602582645', 'lejla.majic', '7lejla');
INSERT INTO `kupac` (`kupac_id`, `ime`, `prezime`, `grad`, `adresa`, `telefon`, `user`, `pass`) VALUES (8, 'Zaim', 'Rošić', 'Banja Luka', 'Gajeva 88', '062589987', 'zaim.rosic', '8zaim');
INSERT INTO `kupac` (`kupac_id`, `ime`, `prezime`, `grad`, `adresa`, `telefon`, `user`, `pass`) VALUES (9, 'Nevena', 'Melin', 'Mostar', 'Rizikala 6', '065325698', 'nevena.melin', '9nevena');
INSERT INTO `kupac` (`kupac_id`, `ime`, `prezime`, `grad`, `adresa`, `telefon`, `user`, `pass`) VALUES (10, 'Tahir', 'Spaho', 'Tešanj', 'Rudolfa Zaplate 21', '062555444', 'tahir.spaho', '10tahir');
